### ISSUE TITLE
403 when non-admin tries to get a team

### ISSUE THREAD

**Issue by gempain** [getmeli/meli#179]
Following the [comment](https://github.com/getmeli/meli/issues/177#issuecomment-756101054) from @robertorubioguardia.

---

HI @gempain

I managed to add GitHub authentication and accept the invite following your instructions and then added the user as a member of a team in my organization, with no admin powers.

Thing is, when I log in from the new invited user, I get a 403 error in the GUI where the teams should be listed.
The API error in the console is:

```
{
"statusCode": 403,
"path": "/api/v1/teams/b6ddb484-0feb-4ae7-bf78-45aeaed6f67f/sites",
"message": "Cannot get team"
}
```

If I add the user to the team with admin powers, there is no error. I have also confirmed the team ID is valid.

Cheers.

**Comment by gempain** [comment]
@robertorubioguardia a fix has been released in v1.0.0-beta.12. Can you confirm this is working for you ?

**Comment by robertorubioguardia** [comment]
Hi mate.

I did a docker system prune to delete all images, then docker-compose down and up again and the problem persists.

Am I missing something to get the latest code?

Cheers,

**Comment by gempain** [comment]
I don't think doing a system prune helps in this case, at least not in the order you mentioned. To pull the latest images, all you have to do is:

```shell
docker-compose pull
docker-compose up -d
```

There's no need to `down` anything 😄

**Comment by robertorubioguardia** [comment]
Hi @gempain 

Thanks mate 😆  I am new in dockerland and still fiding my way around it. 

The fox worked like a charm.

Is it ok if I keep coming with issues, etc? I am really into Meli but dont want to bug you too much :)

**Comment by gempain** [comment]
@robertorubioguardia I'm glad it helped ! Docker and Docker Compose are awesome, I'm sure you'll love it 😄 

You are very welcome to open as many issues as you want. It helps other users that might have the same issues as you. You may as well join our chat if you'd just like to ask general questions. I'd be happy to learn about why you're using Meli and how it helps you, so head out [here](https://discord.gg/TFTaCUEdX6) 🚀 

I'll close this issue, but you may continue replying and we will reopen if needed.

Enjoy Meli !
